const ActionTypes = {
  FETCHING_SUCCESS: 'FETCHING_SUCCESS',
  FETCHING_ERROR: 'FETCHING_ERROR',
  LOADING_TRUE: 'LOADING_TRUE',
  FILTER_SUCCESS: 'FILTER_SUCCESS',
  CHANGE_INPUT: 'CHANGE_INPUT',
  SORTING_SUCCEED: 'SORTING_SUCCEED',
  RESET_SORT: 'RESET_SORT',
  RESET: 'RESET',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CLEAR_INPUT: 'CLEAR_INPUT',
  CHANGE_DROPDOWN_MENU_NUMBERS: 'CHANGE_DROPDOWN_MENU_NUMBERS',
  CHANGE_SHOULD_EXECUTE_COUNT_DATA: 'CHANGE_SHOULD_EXECUTE_COUNT_DATA',
  CHANGE_DATA_TO_COUNT: 'CHANGE_DATA_TO_COUNT',
};

export default ActionTypes;
